# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitoring.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10monitoring.proto\x12\nmonitoring\"g\n\x0eMonitoringData\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x0e\n\x06metric\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x01\x12\x11\n\tclient_id\x18\x05 \x01(\t\"\\\n\x07\x43ommand\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ommand_type\x18\x02 \x01(\t\x12\x14\n\x0c\x63ommand_data\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"l\n\x0f\x43ommandResponse\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0e\n\x06output\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x11\n\tclient_id\x18\x05 \x01(\t2[\n\x11MonitoringService\x12\x46\n\rMonitorStream\x12\x1a.monitoring.MonitoringData\x1a\x13.monitoring.Command\"\x00(\x01\x30\x01\x62\x06proto3')



_MONITORINGDATA = DESCRIPTOR.message_types_by_name['MonitoringData']
_COMMAND = DESCRIPTOR.message_types_by_name['Command']
_COMMANDRESPONSE = DESCRIPTOR.message_types_by_name['CommandResponse']
MonitoringData = _reflection.GeneratedProtocolMessageType('MonitoringData', (_message.Message,), {
  'DESCRIPTOR' : _MONITORINGDATA,
  '__module__' : 'monitoring_pb2'
  # @@protoc_insertion_point(class_scope:monitoring.MonitoringData)
  })
_sym_db.RegisterMessage(MonitoringData)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'monitoring_pb2'
  # @@protoc_insertion_point(class_scope:monitoring.Command)
  })
_sym_db.RegisterMessage(Command)

CommandResponse = _reflection.GeneratedProtocolMessageType('CommandResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDRESPONSE,
  '__module__' : 'monitoring_pb2'
  # @@protoc_insertion_point(class_scope:monitoring.CommandResponse)
  })
_sym_db.RegisterMessage(CommandResponse)

_MONITORINGSERVICE = DESCRIPTOR.services_by_name['MonitoringService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MONITORINGDATA._serialized_start=32
  _MONITORINGDATA._serialized_end=135
  _COMMAND._serialized_start=137
  _COMMAND._serialized_end=229
  _COMMANDRESPONSE._serialized_start=231
  _COMMANDRESPONSE._serialized_end=339
  _MONITORINGSERVICE._serialized_start=341
  _MONITORINGSERVICE._serialized_end=432
# @@protoc_insertion_point(module_scope)
