# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import monitoring_pb2 as monitoring__pb2


class MonitoringServiceStub(object):
    """Monitoring service with bidirectional streaming
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MonitorStream = channel.stream_stream(
                '/monitoring.MonitoringService/MonitorStream',
                request_serializer=monitoring__pb2.MonitoringData.SerializeToString,
                response_deserializer=monitoring__pb2.Command.FromString,
                )


class MonitoringServiceServicer(object):
    """Monitoring service with bidirectional streaming
    """

    def MonitorStream(self, request_iterator, context):
        """Bidirectional streaming: clients send monitoring data and receive commands
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitoringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MonitorStream': grpc.stream_stream_rpc_method_handler(
                    servicer.MonitorStream,
                    request_deserializer=monitoring__pb2.MonitoringData.FromString,
                    response_serializer=monitoring__pb2.Command.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'monitoring.MonitoringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MonitoringService(object):
    """Monitoring service with bidirectional streaming
    """

    @staticmethod
    def MonitorStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/monitoring.MonitoringService/MonitorStream',
            monitoring__pb2.MonitoringData.SerializeToString,
            monitoring__pb2.Command.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
